<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.7 on win32)" generated="20210131 18:39:42.249" rpa="false">
<suite id="s1" name="Selenium First" source="C:\Users\Harsha\PycharmProjects\robot_proj\selenium_proj\selenium_first.robot">
<test id="s1-t1" name="testcase123">
<kw name="pythonm">
<assign>
<var>${result}=</var>
</assign>
<msg timestamp="20210131 18:39:42.379" level="FAIL">No keyword with name 'pythonm' found.</msg>
<status status="FAIL" starttime="20210131 18:39:42.379" endtime="20210131 18:39:42.379"></status>
</kw>
<status status="FAIL" starttime="20210131 18:39:42.377" endtime="20210131 18:39:42.380" critical="yes">No keyword with name 'pythonm' found.</status>
</test>
<status status="FAIL" starttime="20210131 18:39:42.251" endtime="20210131 18:39:42.381"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Selenium First">Selenium First</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210131 18:39:42.375" level="ERROR">Error in file 'C:\Users\Harsha\PycharmProjects\robot_proj\selenium_proj\selenium_first.robot' on line 3: Importing test library '../name' failed: ModuleNotFoundError: No module named '.'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Harsha\PycharmProjects\robot_proj\venv\Scripts\robot.exe
  C:\Users\Harsha\AppData\Local\Programs\Python\Python38\python38.zip
  C:\Users\Harsha\AppData\Local\Programs\Python\Python38\DLLs
  C:\Users\Harsha\AppData\Local\Programs\Python\Python38\lib
  C:\Users\Harsha\AppData\Local\Programs\Python\Python38
  c:\users\harsha\pycharmprojects\robot_proj\venv
  c:\users\harsha\pycharmprojects\robot_proj\venv\lib\site-packages</msg>
</errors>
</robot>
